# -*- coding: utf-8 -*-
"""LR_Seth_Emery.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAuEII9GXD_P2vZCCnxjscxEgXrAhOKj
"""

pip install ISLP

"""Simple Linear Regression"""

# load the dataset
from ISLP import load_data
boston_data = load_data('Boston')
boston_data.head(5)

# specify x1
from ISLP.models import ModelSpec as MS
design = MS(['lstat']) # X1
X = design.fit_transform(boston_data) # intercept
print(X[:4])

y = boston_data['medv'] # grab the y/dependent variable
y.head(5)

# create and train the model
import statsmodels.api as sm

model = sm.OLS(y, X) # create the model
result = model.fit() # train the model

# show model results
from ISLP.models import summarize
summarize(result)

result.summary()

"""# Multiple Linear Regression"""

X = MS(['lstat', 'age', 'rm']).fit_transform(boston_data)
model2 = sm.OLS(y, X)
result2 = model2.fit()
summarize(result2)

"""# Interaction Terms"""

X = MS(['lstat', 'age', ('lstat', 'age')]).fit_transform(boston_data)
model3 = sm.OLS(y,X)
result3 = model3.fit()
summarize(result3)

result3.summary()

"""# Qualitative Predictors"""

carseat_data = load_data('Carseats')
carseat_data.head(5)

all_predictors = list(carseat_data.columns.drop('Sales'))
print(all_predictors)

X = MS(all_predictors).fit_transform(carseat_data)
y = carseat_data['Sales']
model4 = sm.OLS(y,X)
result4 = model4.fit()
summarize(result4)